=== Jabroni/dvbe4sage/trunk/dvbe4sage/Distributive/config.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="configuration">
    <xs:complexType>
      <xs:all>
        <xs:element minOccurs="0" name="general">
          <xs:complexType>
            <xs:all>
              <xs:element minOccurs="0" default="2" name="logLevel" type="xs:unsignedShort" />
            </xs:all>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="SageTVIntegration">
          <xs:complexType>
            <xs:all>
              <xs:element minOccurs="0" default="6969" name="listeningPort" type="xs:unsignedShort" />
            </xs:all>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="recording">
          <xs:complexType>
            <xs:all>
              <xs:element minOccurs="0" default="eng" name="preferredAudioLanguage" type="xs:normalizedString" />
              <xs:element minOccurs="0" default="160000" name="TSPacketsPerOutputBuffer" type="xs:unsignedLong" />
              <xs:element minOccurs="0" default="140" name="TSPacketsOutputThreshold" type="xs:unsignedLong" />
              <xs:element minOccurs="0" default="false" name="disableWriteBuffering" type="xs:boolean" />
              <xs:element minOccurs="0" default="1" name="PATDilutionFactor" type="xs:unsignedLong" />
              <xs:element minOccurs="0" default="1" name="PMTDilutionFactor" type="xs:unsignedLong" />
            </xs:all>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="tuning">
          <xs:complexType>
            <xs:all>
              <xs:element minOccurs="0" default="20" name="timeout" type="xs:unsignedShort" />
              <xs:element minOccurs="0" default="5" name="lockTimeout" type="xs:unsignedShort" />
              <xs:element minOccurs="0" default="false" name="useNewMethod" type="xs:boolean" />
              <xs:element minOccurs="0" default="1024" name="TSPacketsPerBuffer" type="xs:unsignedLong" />
              <xs:element minOccurs="0" default="400" name="numberOfBuffers" type="xs:unsignedLong" />
            </xs:all>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="plugins">
          <xs:complexType>
            <xs:all>
              <xs:element minOccurs="0" name="servedCAIDs">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="CAID" type="xs:hexBinary" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" default="5" name="DCWTimeout" type="xs:unsignedShort" />
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Jabroni/dvbe4sage/dvbe4sage/Distributive/config.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">
  <general>
    <logLevel>2</logLevel>
  </general>
  <SageTVIntegration>
    <listeningPort>6969</listeningPort>
  </SageTVIntegration>
  <plugins>
    <DCWTimeout>5</DCWTimeout>
  </plugins>
  <recording>
    <disableWriteBuffering>false</disableWriteBuffering>
    <preferredAudioLanguage>eng</preferredAudioLanguage>
    <TSPacketsOutputThreshold>140</TSPacketsOutputThreshold>
    <TSPacketsPerOutputBuffer>160000</TSPacketsPerOutputBuffer>
    <PATDilutionFactor>1</PATDilutionFactor>
    <PMTDilutionFactor>1</PMTDilutionFactor>
  </recording>
  <tuning>
    <lockTimeout>5</lockTimeout>
    <timeout>20</timeout>
    <useNewMethod>false</useNewMethod>
    <TSPacketsPerBuffer>1024</TSPacketsPerBuffer>
    <numberOfBuffers>400</numberOfBuffers>
  </tuning>
</configuration>
