=== Jabroni/dvbe4sage/dvbe4sage/Distributive/cards.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="Provider">
    <xs:sequence>
      <xs:element minOccurs="0" name="LNB">
        <xs:complexType>
          <xs:attribute name="LOF1" type="xs:unsignedLong" use="optional" />
          <xs:attribute name="LOF2" type="xs:unsignedLong" use="optional" />
          <xs:attribute name="SW" type="xs:unsignedLong" use="optional" />
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="DiSeQ">
        <xs:complexType>
          <xs:attribute name="port" type="xs:unsignedShort" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="Card" abstract="true">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="provider" type="Provider"/>
    </xs:sequence>
    <xs:attribute default="false" name="excluded" type="xs:boolean" use="optional" />
    <xs:attribute default="DVB-S" name="type" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="DVB-S" />
          <xs:enumeration value="DVB-T" />
          <xs:enumeration value="DVB-C" />
          <xs:enumeration value="DVB-S2" />
          <xs:enumeration value="ATSC" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="CardByOrdinal">
    <xs:complexContent mixed="false">
      <xs:extension base="Card">
        <xs:attribute name="ordinal" type="xs:unsignedShort" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="CardByMAC">
    <xs:complexContent mixed="false">
      <xs:extension base="Card">
        <xs:attribute name="MAC" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="[0-9A-Fa-f]{2}:[0-9A-Fa-f]{2}:[0-9A-Fa-f]{2}:[0-9A-Fa-f]{2}:[0-9A-Fa-f]{2}:[0-9A-Fa-f]{2}" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="cards">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="defaultProviders">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="provider" type="Provider" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="card" type="Card" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Jabroni/dvbe4sage/dvbe4sage/Distributive/cards.xml
<?xml version="1.0" encoding="utf-8"?>
<cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cards.xsd">
  <defaultProviders>
    <provider name="YES_DBS">
      <LNB LOF1="9750000" LOF2="10600000" SW="11700000" />
    </provider>
  </defaultProviders>
  <card xsi:type="CardByOrdinal" ordinal="1" type="DVB-S2" />
  <card xsi:type="CardByOrdinal" ordinal="2" excluded="true" />
  <card xsi:type="CardByOrdinal" ordinal="3" type="DVB-S2" />
  <card xsi:type="CardByOrdinal" ordinal="4" type="DVB-S2" />
</cards>
